apiVersion: v1
kind: Service
metadata:
  name: traefik-consul
  namespace: lebleu-system
  labels:
    app: traefik-consul
spec:
  ports:
    - name: http
      port: 8500
    - name: rpc
      port: 8400
    - name: serflan
      port: 8301
    - name: serfwan
      port: 8302
    - name: server
      port: 8300
    - name: consuldns
      port: 8600
  clusterIP: None
  selector:
    app: traefik-consul
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: traefik-consul
  namespace: lebleu-system
  labels:
    app: traefik-consul
spec:
  serviceName: "traefik-consul"
  replicas: 3
  template:
    metadata:
      labels:
        app: traefik-consul
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: traefik-consul
          imagePullPolicy: Always
          image: consul:0.7.5
          args:
            - "agent"
            - "-server"
            - "-client"
            - "0.0.0.0"
            - "-recursor"
            - "8.8.8.8"
            - "-bootstrap-expect"
            - "3"
            - "-retry-join"
            - "traefik-consul"
            - "-ui"
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
          volumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs
            - name: traefik-consul-data
              mountPath: /data
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      volumes:
        - name: ca-certificates
          hostPath:
            path: /usr/share/ca-certificates/
  volumeClaimTemplates:
    - metadata:
        name: traefik-consul-data
        annotations:
          volume.beta.kubernetes.io/storage-class: nfs
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: lebleu-system
  labels:
    app: traefik-init
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "DEBUG"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      #[entryPoints.http.redirect]
      #entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [web]
    [kubernetes]
    [acme]
    email = "webmaster@equipelebleu.com"
    storage = "traefik/acme/account"
    entryPoint = "https"
    onDemand = true
    onHostRule = true
    [consul]
    endpoint = "traefik-consul:8500"
    watch = true
    prefix = "traefik"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: traefik-init
  namespace: lebleu-system
  labels:
    app: traefik-init
spec:
  activeDeadlineSeconds: 60
  template:
    metadata:
      name: traefik-init
      labels:
        app: traefik-init
    spec:
      containers:
        - image: traefik
          name: traefik
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
          args:
            - storeconfig
            - --configfile=/config/traefik.toml
      volumes:
        - name: config
          configMap:
            name: traefik-conf
      restartPolicy: Never